Add copyright header and support for several traces in one KML file.

diff --git a/kmltraceroute b/kmltraceroute
--- a/kmltraceroute
+++ b/kmltraceroute
@@ -1,5 +1,8 @@
 #! /bin/bash
-
+#
+# Copyright: 2017 Petter Reinholdtsen
+#            2017 Anders Einar Hilden
+#
 # 
 # This is free and unencumbered software released into the public domain.
 # 
@@ -27,31 +30,48 @@
 # For more information, please refer to <http://unlicense.org/>
 # 
 
-cat <<HEADER
+header() {
+    cat <<HEADER
 <?xml version="1.0" encoding="UTF-8"?>
 <kml xmlns="http://www.opengis.net/kml/2.2">
   <Document>
 HEADER
+}
 
-LONGLATS=""
-for IP in $(sudo tcptraceroute -n $1 | tail -n +2 | awk '{print $2}' | grep -E '^([0-9]{1,3}[\.]){3}[0-9]{1,3}$'); do 
-#sudo tcptraceroute -n $1 | tail -n +2 | awk '{print $2}' | while read IP; do
-       GEOIP=$(geoiplookup -f GeoLiteCity.dat $IP);
-       if [ "$(echo "$GEOIP" | grep -q "IP Address not found"; echo $?;)" != "0" ]; then
-	   LONG=$(echo "$GEOIP" | cut -d, -f 8)
-	   LAT=$(echo "$GEOIP" | cut -d, -f 7)
-	   LONGLAT="${LONG},${LAT}"
-	   LONGLATS="${LONGLATS}${LONGLAT}\n"
-           echo "<Placemark><name>$IP</name><description>GeoIP position for $IP</description><Point><coordinates>$LONGLAT</coordinates></Point></Placemark>";
-       fi
-done;
+tracehost() {
+    targetip="$1"
+    targetname="$2"
+    LONGLATS=""
+    for IP in $(sudo tcptraceroute -n $targetip | tail -n +2 | awk '{print $2}' | grep -E '^([0-9]{1,3}[\.]){3}[0-9]{1,3}$'); do 
+#sudo tcptraceroute -n $targetip | tail -n +2 | awk '{print $2}' | while read IP; do
+	GEOIP=$(geoiplookup -f GeoLiteCity.dat $IP);
+	if [ "$(echo "$GEOIP" | grep -q "IP Address not found"; echo $?;)" != "0" ]; then
+	    LONG=$(echo "$GEOIP" | cut -d, -f 8)
+	    LAT=$(echo "$GEOIP" | cut -d, -f 7)
+	    LONGLAT="${LONG},${LAT}"
+	    LONGLATS="${LONGLATS}${LONGLAT}\n"
+            echo "<Placemark><name>$IP</name><description>GeoIP position for $IP</description><Point><coordinates>$LONGLAT</coordinates></Point></Placemark>";
+	fi
+    done;
 
-echo "<Placemark><name>Path</name><LineString><coordinates>";
-#echo -e "${LONGLATS::-2}"
-echo -e "$LONGLATS"
-echo "</coordinates></LineString></Placemark>";
+    echo "<Placemark><name>Path</name><LineString><coordinates>";
+    #echo -e "${LONGLATS::-2}"
+    echo -e "$LONGLATS"
+    echo "</coordinates></LineString></Placemark>";
+}
 
-cat <<FOOTER
+footer() {
+    cat <<FOOTER
   </Document>
 </kml>
 FOOTER
+}
+
+header
+for h in "$@" ; do
+    # Trace all locations if host have many IP addresses
+    for ip in $(host $h|awk '/has address/ {print $4}'); do
+	tracehost "$ip" "$h"
+    done
+done
+footer
